function LinksGrabber(k){var l=document,r=k==document?getScrollingElement():k,t=function(a,c){a=a.getBoundingClientRect();return{top:Math.round(a.top+(window.pageYOffset||r.scrollTop)),left:Math.round(a.left+(window.pageXOffset||r.scrollLeft)),width:a.width,height:a.height}};return{collectedLinks:[],markHiddenLinks:function(){for(var a=[],c=l.createNodeIterator(k==document?k.body:k,NodeFilter.SHOW_ELEMENT,null,!1),d;d=c.nextNode();)if(d.childElementCount&&"HTML"!==d.tagName&&d!==k&&(d.offsetHeight<
d.scrollHeight||d.offsetWidth<d.scrollWidth)){var g=l.defaultView.getComputedStyle(d,"");!g||"none"===g.getPropertyValue("display")||"hidden"!==g.getPropertyValue("overflow")&&"hidden"!==g.getPropertyValue("overflow-y")&&"auto"!==g.getPropertyValue("overflow-y")&&"scroll"!=g.getPropertyValue("overflow-y")&&"hidden"!==g.getPropertyValue("overflow-x")&&"auto"!==g.getPropertyValue("overflow-x")&&"scroll"!=g.getPropertyValue("overflow-x")||a.push(d)}a.forEach(function(a){var c=t(a,k);a=a.getElementsByTagName("a");
for(var d=0,f=0;f<a.length;++f){var e=a[f],n=t(e,k);rectsIntersected(c,n)||(e.setAttribute("__fireshotHiddenLink",1),++d)}})},createLinksSnapshot:function(){function a(a){if(a.getAttribute("__fireshotHiddenLink"))return!1;var e=a.href;if(e=e&&""!==e&&"javascript:void(0)"!==e&&e.slice&&"#"!==e.slice(-1)){a:{for(;a&&a!=l;){e=l.defaultView.getComputedStyle(a,"");if("hidden"===e.visibility||"none"===e.display||0==e.opacity){a=!0;break a}a=a.parentNode}a=!1}e=!a}return e}function c(a,f){var e=t(a,k),b=
a.getClientRects(),c=void 0;if(1===b.length){var d;if(b=a.children&&0<a.children.length&&"IMG"===a.children[0].tagName)b=l.defaultView.getComputedStyle(a,""),b=!b||"hidden"!==b.getPropertyValue("overflow")&&"hidden"!==b.getPropertyValue("overflow-y")&&"auto"!==b.getPropertyValue("overflow-y")&&"scroll"!=b.getPropertyValue("overflow-y")&&"hidden"!==b.getPropertyValue("overflow-x")&&"auto"!==b.getPropertyValue("overflow-x")&&"scroll"!=b.getPropertyValue("overflow-x")?t(a.children[0],k):void 0,b=d=b;
b&&0<d.width&&0<d.height?f.push(d):f.push(e)}else{for(a=0;a<b.length;++a)0===a?c={left:b[a].left,top:b[a].top}:(b[a].left<c.left&&(c.left=b[a].left),b[a].top<c.top&&(c.top=b[a].top));if(c)for(d=e.left-c.left,e=e.top-c.top,a=0;a<b.length;++a)f.push({left:b[a].left+d,top:b[a].top+e,width:b[a].width,height:b[a].height})}}for(var d=k.getElementsByTagName("a"),g={left:0,top:0,width:window.innerWidth,height:window.innerHeight},f=0;f<d.length;++f){var h=d[f];if(a(h)){var q=h.getBoundingClientRect();if(rectsIntersected(q,
g)&&(q=[],c(h,q),0!==q.length)){var m=h.getAttribute("__fireshotLinkId");m?m=parseInt(m):(m=this.collectedLinks.length,h.setAttribute("__fireshotLinkId",m));this.collectedLinks[m]={e:h,r:q}}}}},getLinks:function(a,c){var d=a.crop?a.cropRight-a.cropLeft:a.width,g=a.crop?a.cropBottom-a.cropTop:a.height;a.links=[];for(var f=0;f<this.collectedLinks.length;++f){var h=this.collectedLinks[f],k=this.collectedLinks[f].e;if(!k.getAttribute("__fireshotHiddenLink")){for(var m=[],e=0;e<h.r.length;++e){var n=h.r[e].left-
c.x,p=h.r[e].top-c.y,b=h.r[e].width,l=h.r[e].height;n>=d||p>=g||(0>n&&(b+=n,n=0),0>p&&(l+=p,p=0),n+b>d&&(b=d-n),p+l>g&&(l=g-p),0<b&&0<l&&m.push([Math.round(n*a.ratioW),Math.round(p*a.ratioH),Math.round(b*a.ratioW),Math.round(l*a.ratioH)]))}0<m.length&&a.links.push({a:k.href,r:m,h:""})}}getConsolePtr()("links filtered: "+(this.collectedLinks.length-a.links.length));getConsolePtr()("links added: "+a.links.length)},checkClickableLinks:function(){for(var a,c,d=r.scrollLeft,g=r.scrollTop,f=0;f<this.collectedLinks.length;++f)if(!this.collectedLinks[f].p){a=
this.collectedLinks[f].r[0].left-d;c=this.collectedLinks[f].r[0].top-g;0>a&&(a+=this.collectedLinks[f].r[0].width);0>c&&(c+=this.collectedLinks[f].r[0].height);var h;0<=c&&c<=window.innerHeight&&0<=a&&a<=window.innerWidth&&((h=document.elementFromPoint(Math.round(a+.5),Math.round(c+.5)))===this.collectedLinks[f].e||h&&this.collectedLinks[f].e.contains(h)||this.collectedLinks[f].e.setAttribute("__fireshotHiddenLink",1))}},clearAttributes:function(){for(var a=k.getElementsByTagName("a"),c=0;c<a.length;++c)a[c].removeAttribute("__fireshotHiddenLink"),
a[c].removeAttribute("__fireshotLinkId")}}};
